# Generated by Django 5.1.5 on 2025-02-19 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název projektu')),
                ('description', models.TextField(blank=True, verbose_name='Popis projektu')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='tracker.project', verbose_name='Projekt')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('work_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tracker.workrecord')),
            ],
        ),
    ]
