# Generated by Django 5.1.5 on 2025-02-06 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrecord',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='note',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='start_time',
        ),
        migrations.AddField(
            model_name='workrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
