# Generated by Django 5.1.5 on 2025-02-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_workrecord_end_time_remove_workrecord_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
