# Generated by Django 5.1.5 on 2025-02-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_workrecord_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Uzavřený projekt'),
        ),
    ]
