# Generated by Django 4.2.23 on 2025-08-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_project_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodocumentation',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default.jpg', null=True, upload_to='photos/'),
        ),
    ]
