# Generated by Django 4.2.23 on 2025-08-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_workrecord_options_projectmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-01 12:00:00'),
            preserve_default=False,
        ),
    ]
