# Generated by Django 4.2.23 on 2025-08-12 08:30

from django.db import migrations, models
import django.utils.timezone   
from django.utils import timezone 

def set_created_at_from_date(apps, schema_editor):
    WorkRecord = apps.get_model('tracker', 'WorkRecord')
    for wr in WorkRecord.objects.all():
        wr.created_at = timezone.make_aware(
            timezone.datetime.combine(wr.date, timezone.datetime.min.time())
        )
        wr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_workrecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(set_created_at_from_date, reverse_code=migrations.RunPython.noop),
    ]
