# Generated by Django 4.2.23 on 2025-10-06 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_workrecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
