# Generated by Django 4.2.23 on 2025-10-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_workrecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Zeměpisná šířka (latitude, např. 49.684)', null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Zeměpisná délka (longitude, např. 18.676)', null=True),
        ),
    ]
