# Generated by Django 4.2.23 on 2025-11-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_workrecord_latitude_workrecord_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='dbh_cm',
            field=models.FloatField(blank=True, help_text='Průměr kmene v centimetrech v měřické výšce.', null=True, verbose_name='Průměr kmene (DBH) [cm]'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='height_m',
            field=models.FloatField(blank=True, help_text='Výška stromu v metrech.', null=True, verbose_name='Výška stromu [m]'),
        ),
        migrations.CreateModel(
            name='TreeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physiological_age', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 – mladý jedinec ve fázi ujímání'), (2, '2 – aklimatizovaný mladý strom'), (3, '3 – dospívající jedinec'), (4, '4 – dospělý jedinec'), (5, '5 – senescentní jedinec')], null=True, verbose_name='Fyziologické stáří')),
                ('vitality', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 – výborná až mírně snížená'), (2, '2 – zřetelně snížená'), (3, '3 – výrazně snížená'), (4, '4 – zbytková'), (5, '5 – suchý (mrtvý) strom')], null=True, verbose_name='Vitalita')),
                ('health_state', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 – výborný až dobrý'), (2, '2 – zhoršený'), (3, '3 – výrazně zhoršený'), (4, '4 – silně narušený'), (5, '5 – kritický / rozpadlý strom')], null=True, verbose_name='Zdravotní stav')),
                ('stability', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 – výborná až dobrá (nenarušená)'), (2, '2 – zhoršená'), (3, '3 – výrazně zhoršená'), (4, '4 – silně narušená'), (5, '5 – kritická')], null=True, verbose_name='Stabilita')),
                ('perspective', models.CharField(blank=True, choices=[('a', 'a – dlouhodobě perspektivní'), ('b', 'b – krátkodobě perspektivní'), ('c', 'c – neperspektivní')], max_length=1, null=True, verbose_name='Perspektiva stromu')),
                ('work_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='tracker.workrecord', verbose_name='Pracovní záznam')),
            ],
            options={
                'verbose_name': 'Hodnocení stromu',
                'verbose_name_plural': 'Hodnocení stromů',
            },
        ),
    ]
