# Generated by Django 4.2.23 on 2025-11-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_workrecord_dbh_cm_workrecord_height_m_treeassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrecord',
            name='dbh_cm',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='height_m',
        ),
        migrations.AddField(
            model_name='treeassessment',
            name='dbh_cm',
            field=models.FloatField(blank=True, help_text='Průměr kmene v centimetrech v měřické výšce.', null=True, verbose_name='Průměr kmene (DBH) [cm]'),
        ),
        migrations.AddField(
            model_name='treeassessment',
            name='height_m',
            field=models.FloatField(blank=True, help_text='Výška stromu v metrech.', null=True, verbose_name='Výška stromu [m]'),
        ),
    ]
