# Generated by Django 4.2.23 on 2025-11-27 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_remove_workrecord_dbh_cm_remove_workrecord_height_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeassessment',
            name='assessed_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum hodnocení'),
        ),
        migrations.AlterField(
            model_name='treeassessment',
            name='work_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='tracker.workrecord', verbose_name='Pracovní záznam'),
        ),
    ]
