# Generated by Django 4.2.23 on 2025-11-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_treeassessment_assessed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='external_tree_id',
            field=models.CharField(blank=True, help_text='Číslo stromu z papírové inventarizace, cedulek nebo jiného systému.', max_length=50, null=True, verbose_name='Číslo stromu (externí)'),
        ),
    ]
