# Generated by Django 4.2.23 on 2025-11-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_workrecord_external_tree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='taxon',
            field=models.CharField(blank=True, help_text='Botanický název stromu.', max_length=200, verbose_name='Taxon'),
        ),
    ]
