# Generated by Django 4.2.23 on 2025-12-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_species'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='species',
            new_name='tracker_spe_latin_n_13264f_idx',
            old_name='tracker_spec_latin_name_idx',
        ),
        migrations.RenameIndex(
            model_name='species',
            new_name='tracker_spe_czech_n_a56e77_idx',
            old_name='tracker_spec_czech_name_idx',
        ),
        migrations.AlterField(
            model_name='species',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
