# Generated by Django 4.2.23 on 2025-12-05 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0017_rename_tracker_spec_latin_name_idx_tracker_spe_latin_n_13264f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Typ zásahu')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Pořadí')),
            ],
            options={
                'verbose_name': 'Typ zásahu',
                'verbose_name_plural': 'Typy zásahů',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TreeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Popis zásahu')),
                ('priority', models.CharField(choices=[('urgent', 'Urgentní'), ('high', 'Vysoká'), ('normal', 'Normální'), ('low', 'Nízká')], default='normal', max_length=10, verbose_name='Priorita')),
                ('status', models.CharField(choices=[('draft', 'Návrh'), ('pending_approval', 'Ke schválení'), ('approved', 'Schváleno'), ('in_progress', 'Probíhá'), ('pending_check', 'Ke kontrole'), ('completed', 'Dokončeno'), ('rework_required', 'Reklamace')], default='draft', max_length=32, verbose_name='Stav zásahu')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Termín zásahu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL, verbose_name='Zodpovědný')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interventions', to=settings.AUTH_USER_MODEL, verbose_name='Navrhl')),
                ('intervention_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.interventiontype', verbose_name='Typ zásahu')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='tracker.workrecord', verbose_name='Strom')),
            ],
            options={
                'verbose_name': 'Zásah na stromě',
                'verbose_name_plural': 'Zásahy na stromě',
                'ordering': ['status', 'due_date', 'id'],
            },
        ),
    ]
