# Generated by Django 4.2.23 on 2025-12-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_interventiontype_treeintervention'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treeintervention',
            options={'ordering': ['status', 'urgency', 'due_date', 'id'], 'verbose_name': 'Zásah na stromě', 'verbose_name_plural': 'Zásahy na stromě'},
        ),
        migrations.RemoveField(
            model_name='treeintervention',
            name='priority',
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='code',
            field=models.CharField(default='legacy', max_length=20, unique=True, verbose_name='Kód technologie'),
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='note_hint',
            field=models.TextField(blank=True, verbose_name='Pokyny k doplnění'),
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='note_required',
            field=models.BooleanField(default=False, verbose_name='Vyžaduje doplnění poznámky'),
        ),
        migrations.AddField(
            model_name='treeintervention',
            name='urgency',
            field=models.IntegerField(choices=[(0, '0 – okamžitě, riziko z prodlení'), (1, '1 – první etapa prací'), (2, '2 – druhá etapa prací'), (3, '3 – třetí etapa prací')], default=2, verbose_name='Naléhavost'),
        ),
        migrations.AlterField(
            model_name='interventiontype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Název technologie'),
        ),
    ]
