# Generated by Django 4.2.23 on 2025-12-05 09:27

from django.db import migrations

SPPK_TYPES = [
    {"code": "S-RZK", "name": "Řez zapěstování koruny", "category": "Řez stromů"},
    {"code": "S-RK", "name": "Řez komparativní", "category": "Řez stromů"},
    {"code": "S-RV", "name": "Řez výchovný", "category": "Řez stromů"},
    {"code": "S-RZ", "name": "Řez zdravotní", "category": "Řez stromů"},
    {"code": "S-RB", "name": "Řez bezpečnostní", "category": "Řez stromů"},
    {
        "code": "S-RLSP",
        "name": "Lokální redukce směrem k překážce",
        "category": "Řez stromů",
        "note_required": True,
        "note_hint": "Uveďte záměr řezu.",
    },
    {
        "code": "S-RLLR",
        "name": "Lokální redukce z důvodu stabilizace",
        "category": "Řez stromů",
        "note_required": True,
        "note_hint": "Uveďte záměr řezu.",
    },
    {"code": "S-RLPV", "name": "Úprava průjezdného či průchozího profilu", "category": "Řez stromů"},
    {"code": "S-OV", "name": "Odstranění výmladků", "category": "Řez stromů"},
    {
        "code": "S-RO",
        "name": "Redukce obvodová",
        "category": "Řez stromů",
        "note_required": True,
        "note_hint": "Uveďte rozsah redukce.",
    },
    {
        "code": "S-SSK",
        "name": "Stabilizace sekundární koruny",
        "category": "Řez stromů",
        "note_required": True,
        "note_hint": "Uveďte rozsah redukce.",
    },
    {
        "code": "S-RS",
        "name": "Řez sesazovací",
        "category": "Řez stromů",
        "note_required": True,
        "note_hint": "Uveďte rozsah sesazení.",
    },
    {"code": "S-RTHL", "name": "Řez na hlavu", "category": "Řez stromů"},
    {"code": "S-RTPP", "name": "Řez popouštěcí", "category": "Řez stromů"},
    {
        "code": "S-RTZP",
        "name": "Řez živých plotů a stěn",
        "category": "Řez stromů",
        "note_required": True,
        "note_hint": "Uveďte výšku a šířku.",
    },
    {"code": "O-RK", "name": "Řez na korunku ovocných stromů", "category": "Řez ovocných stromů"},
    {"code": "O-RV", "name": "Řez výchovný ovocných dřevin", "category": "Řez ovocných stromů"},
    {"code": "O-RP", "name": "Řez prosvětlovací – průklest", "category": "Řez ovocných stromů"},
    {"code": "O-RO", "name": "Řez opravný", "category": "Řez ovocných stromů"},
    {"code": "O-RA", "name": "Řez zdravotní – asanační", "category": "Řez ovocných stromů"},
    {"code": "O-OV", "name": "Odstranění vlků a výmladků", "category": "Řez ovocných stromů"},
    {"code": "O-RZM", "name": "Řez zmlazovací mírný", "category": "Řez ovocných stromů"},
    {"code": "O-RZS", "name": "Řez zmlazovací střední", "category": "Řez ovocných stromů"},
    {"code": "O-RZH", "name": "Řez zmlazovací hluboký", "category": "Řez ovocných stromů"},
    {
        "code": "S-KV",
        "name": "Kácení stromů volné",
        "category": "Kácení",
        "note_required": True,
        "note_hint": "Uveďte možnost provozu mechanizace.",
    },
    {
        "code": "S-KSP",
        "name": "Kácení s přetažením",
        "category": "Kácení",
        "note_required": True,
        "note_hint": "Uveďte možnost provozu mechanizace.",
    },
    {
        "code": "S-KPV",
        "name": "Postupné kácení – volná plocha",
        "category": "Kácení",
        "note_required": True,
        "note_hint": "Uveďte možnost provozu mechanizace.",
    },
    {
        "code": "S-KPP",
        "name": "Postupné kácení – překážka",
        "category": "Kácení",
        "note_required": True,
        "note_hint": "Uveďte možnost provozu mechanizace.",
    },
    {"code": "S-US", "name": "Úprava pařezu seříznutím", "category": "Kácení"},
    {"code": "S-OR", "name": "Odstranění pařezu ruční", "category": "Kácení"},
    {"code": "S-OK", "name": "Odstranění pařezu mechanizací", "category": "Kácení"},
    {"code": "S-OF", "name": "Odstranění pařezu frézováním", "category": "Kácení"},
    {
        "code": "S-HRI",
        "name": "Instalace hromosvodu",
        "category": "Speciální zásahy",
        "note_required": True,
        "note_hint": "Vyžaduje projektovou dokumentaci.",
    },
    {"code": "S-HRK", "name": "Revizní kontrola hromosvodu", "category": "Speciální zásahy"},
    {"code": "S-OKT", "name": "Oprava kotvení mladého stromu", "category": "Speciální zásahy"},
    {"code": "S-OUV", "name": "Oprava úvazku mladého stromu", "category": "Speciální zásahy"},
    {
        "code": "S-TP",
        "name": "Přístrojový test",
        "category": "Speciální zásahy",
        "note_required": True,
        "note_hint": "Uveďte zaměření testu/metodu.",
    },
    {
        "code": "S-TVV",
        "name": "Průzkum detailní ze země",
        "category": "Speciální zásahy",
        "note_required": True,
        "note_hint": "Uveďte zaměření průzkumu.",
    },
    {
        "code": "S-TVL",
        "name": "Průzkum detailní lezecky",
        "category": "Speciální zásahy",
        "note_required": True,
        "note_hint": "Uveďte zaměření průzkumu.",
    },
    {
        "code": "S-VDD",
        "name": "Dynamická vazba dolní úroveň",
        "category": "Speciální zásahy",
        "note_required": True,
        "note_hint": "Uveďte počet lan a dimenzování.",
    },
    {
        "code": "S-VDH",
        "name": "Dynamická vazba horní úroveň",
        "category": "Speciální zásahy",
        "note_required": True,
        "note_hint": "Uveďte počet lan a dimenzování.",
    },
    {
        "code": "S-VSV",
        "name": "Statická vazba vrtaná",
        "category": "Speciální zásahy",
        "note_required": True,
        "note_hint": "Uveďte počet lan a dimenzování.",
    },
    {
        "code": "S-VSP",
        "name": "Statická vazba podkladnicová",
        "category": "Speciální zásahy",
        "note_required": True,
        "note_hint": "Uveďte počet lan a dimenzování.",
    },
    {
        "code": "S-VO",
        "name": "Instalace obruče",
        "category": "Speciální zásahy",
        "note_required": True,
        "note_hint": "Specifikujte obruč.",
    },
    {
        "code": "S-VP",
        "name": "Instalace podpěry",
        "category": "Speciální zásahy",
        "note_required": True,
        "note_hint": "Uveďte počet podpěr.",
    },
    {"code": "S-VK", "name": "Revize vazby lezecky", "category": "Speciální zásahy"},
    {"code": "PB-RO", "name": "Řízená obvodová redukce – stabilita", "category": "Senescentní péče"},
    {"code": "PB-RR", "name": "Řízená obvodová redukce – revitalizace", "category": "Senescentní péče"},
    {"code": "PB-RB", "name": "Bezpečnostní řez senescentních stromů", "category": "Senescentní péče"},
    {"code": "PB-RLLR", "name": "Lokální redukce – stabilita", "category": "Senescentní péče"},
    {"code": "PB-SSK", "name": "Sesazení sekundární koruny", "category": "Senescentní péče"},
    {"code": "PB-RT", "name": "Přepěstování torza", "category": "Senescentní péče"},
    {"code": "PB-ST", "name": "Sesazení na torzo", "category": "Senescentní péče"},
    {
        "code": "PB-OU",
        "name": "Management okolního porostu",
        "category": "Senescentní péče",
        "note_required": True,
        "note_hint": "Specifikujte formu a rozsah.",
    },
    {"code": "PB-OS", "name": "Úprava stanovištních poměrů", "category": "Senescentní péče"},
    {"code": "PB-KO", "name": "Konzervační ošetření ran", "category": "Senescentní péče"},
    {"code": "PB-KZ", "name": "Konzervační ošetření dutin", "category": "Senescentní péče"},
    {"code": "PB-ZZ", "name": "Ochrana proti zvířatům", "category": "Senescentní péče"},
    {"code": "PB-PS", "name": "Přesadba stromu", "category": "Senescentní péče"},
    {"code": "PB-CH", "name": "Kořenová chránička", "category": "Senescentní péče"},
    {"code": "PB-MH", "name": "Ochrana proti hmyzím škůdcům", "category": "Senescentní péče"},
    {"code": "PB-CP", "name": "Postřik proti chorobám/škůdcům", "category": "Senescentní péče"},
    {"code": "PB-CI", "name": "Mikro/makroinjektáž", "category": "Senescentní péče"},
    {"code": "PB-JO", "name": "Odstraňování poloparazitů", "category": "Senescentní péče"},
    {"code": "PB-LO", "name": "Odstranění lián", "category": "Senescentní péče"},
    {"code": "PB-LR", "name": "Podříznutí lián", "category": "Senescentní péče"},
]


def load_sppk_intervention_types(apps, schema_editor):
    InterventionType = apps.get_model('tracker', 'InterventionType')
    for order, entry in enumerate(SPPK_TYPES, start=1):
        InterventionType.objects.update_or_create(
            code=entry['code'],
            defaults={
                'name': entry['name'],
                'category': entry['category'],
                'note_required': entry.get('note_required', False),
                'note_hint': entry.get('note_hint', ''),
                'order': order,
                'is_active': True,
                'description': '',
            },
        )


def unload_sppk_intervention_types(apps, schema_editor):
    InterventionType = apps.get_model('tracker', 'InterventionType')
    codes = [entry['code'] for entry in SPPK_TYPES]
    InterventionType.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_alter_treeintervention_options_and_more'),
    ]

    operations = [
        migrations.RunPython(load_sppk_intervention_types, unload_sppk_intervention_types),
    ]
