# Generated by Django 4.2.23 on 2025-12-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_load_sppk_interventions'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeintervention',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Schv\xa0leno dne'),
        ),
        migrations.AddField(
            model_name='treeintervention',
            name='handed_over_for_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pýed\xa0no ke kontrole dne'),
        ),
    ]
