# Generated by Django 4.2.23 on 2025-12-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_treeintervention_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeintervention',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Schváleno dne'),
        ),
        migrations.AlterField(
            model_name='treeintervention',
            name='handed_over_for_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Předáno ke kontrole dne'),
        ),
    ]
