# Generated by Django 4.2.23 on 2026-01-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0025_treeassessment_crown_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Zadavatel"),
                    ("FOREMAN", "Stavbyvedoucí"),
                    ("WORKER", "Dělník"),
                ],
                default="WORKER",
                max_length=20,
            ),
        ),
    ]
