# Generated by Django 4.2.23 on 2026-01-13 13:10

from django.db import migrations, models


def map_treeintervention_statuses(apps, schema_editor):
    TreeIntervention = apps.get_model("tracker", "TreeIntervention")
    mapping = {
        "draft": "proposed",
        "pending_approval": "proposed",
        "rework_required": "proposed",
        "approved": "proposed",
        "in_progress": "proposed",
        "pending_check": "done_pending_owner",
        "completed": "completed",
        "proposed": "proposed",
        "done_pending_owner": "done_pending_owner",
    }
    for old_status, new_status in mapping.items():
        TreeIntervention.objects.filter(status=old_status).update(status=new_status)


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0026_alter_projectmembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="treeintervention",
            name="status_note",
            field=models.TextField(blank=True, verbose_name="Poznámka ke stavu"),
        ),
        migrations.RunPython(map_treeintervention_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="treeintervention",
            name="status",
            field=models.CharField(
                choices=[
                    ("proposed", "Navrženo"),
                    ("done_pending_owner", "Hotovo – čeká na potvrzení"),
                    ("completed", "Potvrzeno"),
                ],
                default="proposed",
                max_length=32,
                verbose_name="Stav zásahu",
            ),
        ),
    ]
