# Generated by Django 4.2.23 on 2026-01-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0028_workrecord_cadastre_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
