# Generated by Django 4.2.23 on 2026-01-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0029_fix_workrecord_created_at_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuianCadastralArea",
            fields=[
                ("code", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Ruian cadastral area",
                "verbose_name_plural": "Ruian cadastral areas",
            },
        ),
        migrations.CreateModel(
            name="RuianImportMeta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("source_url", models.CharField(blank=True, default="", max_length=512)),
                ("source_zip_name", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "verbose_name": "Ruian import meta",
                "verbose_name_plural": "Ruian import meta",
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="RuianMunicipality",
            fields=[
                ("code", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Ruian municipality",
                "verbose_name_plural": "Ruian municipalities",
            },
        ),
        migrations.CreateModel(
            name="RuianCadastralAreaMunicipality",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cadastral_area",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="municipality_links",
                        to="tracker.ruiancadastralarea",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="cadastral_area_links",
                        to="tracker.ruianmunicipality",
                    ),
                ),
            ],
            options={
                "unique_together": {("cadastral_area", "municipality")},
            },
        ),
        migrations.AddIndex(
            model_name="ruiancadastralareamunicipality",
            index=models.Index(fields=["cadastral_area", "municipality"], name="tracker_ruianc_cadastr_536f47_idx"),
        ),
        migrations.AddIndex(
            model_name="ruiancadastralareamunicipality",
            index=models.Index(fields=["municipality"], name="tracker_ruianc_municip_12a0a7_idx"),
        ),
    ]
