# Generated by Django 4.2.23 on 2026-01-23 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0030_ruian_lookup_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="workrecord",
            name="vegetation_type",
            field=models.CharField(
                blank=True,
                choices=[("TREE", "Strom"), ("SHRUB", "Keř"), ("HEDGE", "Živý plot")],
                max_length=10,
                null=True,
                verbose_name="Typ vegetace",
            ),
        ),
        migrations.AddField(
            model_name="workrecord",
            name="passport_no",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Pasportní číslo",
            ),
        ),
        migrations.AddField(
            model_name="workrecord",
            name="passport_code",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name="Pasportní kód",
            ),
        ),
        migrations.CreateModel(
            name="ProjectSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "vegetation_type",
                    models.CharField(
                        choices=[("TREE", "Strom"), ("SHRUB", "Keř"), ("HEDGE", "Živý plot")],
                        max_length=10,
                    ),
                ),
                ("next_value", models.PositiveIntegerField(default=1)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences",
                        to="tracker.project",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="projectsequence",
            constraint=models.UniqueConstraint(
                fields=("project", "vegetation_type"),
                name="unique_sequence_per_project_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="workrecord",
            constraint=models.UniqueConstraint(
                fields=("project", "vegetation_type", "passport_no"),
                name="unique_passport_no_per_project_type",
            ),
        ),
    ]
