# Generated by Django 4.2.23 on 2026-01-24 14:40

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0031_passport_sequences"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShrubAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assessed_at", models.DateField(default=timezone.now, verbose_name="Datum hodnocení")),
                ("vitality", models.PositiveSmallIntegerField(blank=True, choices=[(1, "1 – výborná až mírně snížená"), (2, "2 – zřetelně snížená"), (3, "3 – výrazně snížená"), (4, "4 – zbytková"), (5, "5 – suchý (mrtvý) strom")], null=True, verbose_name="Vitalita")),
                ("height_m", models.FloatField(blank=True, null=True, verbose_name="Výška keře [m]")),
                ("width_m", models.FloatField(blank=True, null=True, verbose_name="Šířka keře [m]")),
                ("note", models.TextField(blank=True, verbose_name="Poznámka")),
                ("work_record", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shrub_assessments", to="tracker.workrecord", verbose_name="Pracovní záznam")),
            ],
            options={
                "verbose_name": "Hodnocení keře",
                "verbose_name_plural": "Hodnocení keřů",
            },
        ),
    ]
