# Generated by Django 4.2.23 on 2026-01-24 14:55

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0032_shrubassessment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shrubassessment",
            name="assessed_at",
            field=models.DateField(default=timezone.localdate, verbose_name="Datum hodnocení"),
        ),
    ]
