# Generated by Django 4.2.23 on 2026-02-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_treeassessment_mistletoe_level'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ruiancadastralareamunicipality',
            new_name='tracker_rui_cadastr_985d1c_idx',
            old_name='tracker_ruianc_cadastr_536f47_idx',
        ),
        migrations.RenameIndex(
            model_name='ruiancadastralareamunicipality',
            new_name='tracker_rui_municip_e06f16_idx',
            old_name='tracker_ruianc_municip_12a0a7_idx',
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='vegetation_type',
            field=models.CharField(blank=True, choices=[('TREE', 'Strom'), ('SHRUB', 'Keř'), ('HEDGE', 'Živý plot')], default='TREE', max_length=10, null=True, verbose_name='Typ vegetace'),
        ),
    ]
