# Generated by Django 4.2.23 on 2026-02-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_treeassessment_access_obstacle_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeassessment',
            name='access_obstacle_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Volné stanoviště'), (1, 'Pomístní překážky'), (2, 'Omezená přístupnost / plné spouštění')], default=0, help_text='Kategorie překážek a přístupnosti pro plánování zásahu.', verbose_name='Překážky'),
        ),
    ]
