# Generated by Django 4.2.23 on 2026-02-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0040_alter_treeassessment_access_obstacle_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeintervention',
            name='estimated_price_breakdown',
            field=models.JSONField(blank=True, null=True, verbose_name='Rozpad odhadu ceny'),
        ),
        migrations.AddField(
            model_name='treeintervention',
            name='estimated_price_czk',
            field=models.IntegerField(blank=True, null=True, verbose_name='Odhad ceny [Kč]'),
        ),
    ]
