# Generated by Django 4.2.23 on 2026-02-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0041_treeintervention_estimated_price_breakdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Kód ceníku')),
                ('label', models.CharField(max_length=255, verbose_name='Název ceníku')),
                ('imported_at', models.DateTimeField(auto_now=True, verbose_name='Naposledy importováno')),
            ],
            options={
                'verbose_name': 'Verze ceníku',
                'verbose_name_plural': 'Verze ceníků',
                'ordering': ['-imported_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_code', models.CharField(max_length=20, verbose_name='Kód aktivity')),
                ('item_code', models.CharField(max_length=20, verbose_name='Kód položky')),
                ('label', models.TextField(verbose_name='Popis položky')),
                ('unit', models.CharField(default='ks', max_length=20, verbose_name='Jednotka')),
                ('price_czk', models.PositiveIntegerField(verbose_name='Cena [Kč]')),
                ('band_min_m2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pásmo od [m²]')),
                ('band_max_m2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pásmo do [m²]')),
                ('operation_type', models.CharField(default='jine', max_length=32, verbose_name='Typ operace')),
                ('is_combo', models.BooleanField(default=False, verbose_name='Kombinační položka')),
                ('is_memorial_or_special', models.BooleanField(default=False, verbose_name='Památné / výjimečné')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tracker.pricelistversion', verbose_name='Verze ceníku')),
            ],
            options={
                'verbose_name': 'Položka ceníku',
                'verbose_name_plural': 'Položky ceníku',
                'indexes': [models.Index(fields=['version', 'item_code'], name='tracker_pri_version_ff0eba_idx'), models.Index(fields=['activity_code', 'operation_type'], name='tracker_pri_activit_e7ca62_idx')],
                'unique_together': {('version', 'item_code')},
            },
        ),
    ]
