# Generated by Django 4.2.23 on 2026-02-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0042_pricelistversion_pricelistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventiontype',
            name='is_selectable',
            field=models.BooleanField(default=True, verbose_name='Zobrazit ve výběru'),
        ),
    ]
