# Generated by Django 4.2.23 on 2026-05-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0044_photodocumentation_created_at_photo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Správce projektu'), ('FOREMAN', 'Koordinátor'), ('WORKER', 'Pracovník')], default='WORKER', max_length=20),
        ),
    ]
